### ISSUE TITLE
AutoGPT crashes on start

### ISSUE THREAD

**Issue by randompersononinternet69** [gravelBridge/AutoGPT-Discord#11]
```[+] Building 0.0s (0/0)
[+] Building 0.0s (0/0)
Continuous Mode:  ENABLED
WARNING:  Continuous mode is not recommended. It is potentially dangerous and may cause your AI to run forever or carry out actions you would not usually authorise. Use at your own risk.
GPT3.5 Only Mode:  ENABLED
LEGAL:
LEGAL:  DISCLAIMER AND INDEMNIFICATION AGREEMENT
LEGAL:  PLEASE READ THIS DISCLAIMER AND INDEMNIFICATION AGREEMENT CAREFULLY BEFORE USING THE AUTOGPT SYSTEM. BY USING THE AUTOGPT SYSTEM, YOU AGREE TO BE BOUND BY THIS AGREEMENT.
LEGAL:
LEGAL:  Introduction
LEGAL:  AutoGPT (the "System") is a project that connects a GPT-like artificial intelligence system to the internet and allows it to automate tasks. While the System is designed to be useful and efficient, there may be instances where the System could perform actions that may cause harm or have unintended consequences.
LEGAL:
LEGAL:  No Liability for Actions of the System
LEGAL:  The developers, contributors, and maintainers of the AutoGPT project (collectively, the "Project Parties") make no warranties or representations, express or implied, about the System's performance, accuracy, reliability, or safety. By using the System, you understand and agree that the Project Parties shall not be liable for any actions taken by the System or any consequences resulting from such actions.
LEGAL:
LEGAL:  User Responsibility and Respondeat Superior Liability
LEGAL:  As a user of the System, you are responsible for supervising and monitoring the actions of the System while it is operating on your
LEGAL:  behalf. You acknowledge that using the System could expose you to potential liability including but not limited to respondeat superior and you agree to assume all risks and liabilities associated with such potential liability.
LEGAL:
LEGAL:  Indemnification
LEGAL:  By using the System, you agree to indemnify, defend, and hold harmless the Project Parties from and against any and all claims, liabilities, damages, losses, or expenses (including reasonable attorneys' fees and costs) arising out of or in connection with your use of the System, including, without limitation, any actions taken by the System on your behalf, any failure to properly supervise or monitor the System, and any resulting harm or unintended consequences.
LEGAL:
NEWS:  Welcome to Auto-GPT!
NEWS:  Below you'll find the latest Auto-GPT News and updates regarding features!
NEWS:  If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
NEWS:
NEWS:  Website and Documentation Site 📰📖
NEWS:  Check out https://agpt.co, the official news & updates site for Auto-GPT!
NEWS:  The documentation also has a place here, at https://docs.agpt.co
NEWS:
NEWS:  For contributors 👷🏼
NEWS:  Since releasing v0.3.0, whave been working on re-architecting the Auto-GPT core to make it more extensible and make room for structural performance-oriented R&D.
NEWS:
NEWS:  Check out the contribution guide on our wiki:
NEWS:  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Contributing
NEWS:
NEWS:  🚀 v0.4.1 Release 🚀
NEWS:  Two weeks and 50+ pull requests have passed since v0.4.0, and we are happy to announce the release of v0.4.1!
NEWS:
NEWS:  Highlights and notable changes since v0.4.0:
NEWS:  - The .env.template is more readable and better explains the purpose of each environment variable.
NEWS:  - More dependable search
NEWS:      - The CUSTOM_SEARCH_ENGINE_ID variable has been replaced to GOOGLE_CUSTOM_SEARCH_ENGINE_ID, make sure you update it.
NEWS:  - Better read_file
NEWS:  - More reliable python code execution
NEWS:  - Lots of JSON error fixes
NEWS:  - Directory-based plugins
NEWS:
NEWS:  Further fixes and changes 🛠️
NEWS:  Under the hood, we've done a bunch of work improving architectures and streamlining code. Most of that won't be user-visible
NEWS:
NEWS:  Take a look at the Release Notes on Github for the full changelog!
NEWS:  https://github.com/Significant-Gravitas/Auto-GPT/releases
NEWS:
Requirement already satisfied: abstract-singleton in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 1)) (1.0.1)
Collecting atproto
  Downloading atproto-0.0.14-py3-none-any.whl (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.2/148.2 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: auto_gpt_plugin_template in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 3)) (0.0.2)
Requirement already satisfied: black in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 4)) (23.3.0)Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting build
  Downloading build-0.10.0-py3-none-any.whl (17 kB)
Requirement already satisfied: colorama in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 7)) (0.4.6)
Requirement already satisfied: flake8 in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 8)) (6.0.0)Requirement already satisfied: isort in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 9)) (5.12.0)Collecting newsapi-python
  Downloading newsapi_python-0.2.7-py2.py3-none-any.whl (7.9 kB)
Collecting pandas
  Downloading pandas-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 26.8 MB/s eta 0:00:00
Collecting pylint
  Downloading pylint-2.17.4-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.6/536.6 kB 28.6 MB/s eta 0:00:00
Requirement already satisfied: pytest in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 13)) (7.3.2)
Requirement already satisfied: pytest-cov in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 14)) (4.1.0)
Collecting python-lorem
  Downloading python_lorem-1.3.0.post1-cp310-none-any.whl (9.1 kB)
Collecting python-telegram-bot
  Downloading python_telegram_bot-20.3-py3-none-any.whl (545 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 545.4/545.4 kB 38.3 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 17)) (2.31.0)
Collecting requests-mock
  Downloading requests_mock-1.11.0-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 19)) (65.5.1)
Collecting tweepy==4.13.0
  Downloading tweepy-4.13.0-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.8/102.8 kB 142.4 MB/s eta 0:00:00
Collecting twine
  Downloading twine-4.0.2-py3-none-any.whl (36 kB)
Collecting validators
  Downloading validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: wheel in /usr/local/lib/python3.10/site-packages (from -r plugins/Auto-GPT-Plugins-master/requirements.txt (line 23)) (0.40.0)
Collecting wolframalpha==5.0.0
  Downloading wolframalpha-5.0.0-py3-none-any.whl (7.5 kB)
Collecting requests-oauthlib<2,>=1.2.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting oauthlib<4,>=3.2.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 44.9 MB/s eta 0:00:00
Collecting xmltodict
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Collecting more-itertools
  Downloading more_itertools-9.1.0-py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.2/54.2 kB 136.8 MB/s eta 0:00:00
Collecting jaraco.context
  Downloading jaraco.context-4.3.0-py3-none-any.whl (5.3 kB)
Collecting dacite<1.9.0,>=1.8.0
  Downloading dacite-1.8.1-py3-none-any.whl (14 kB)
Collecting typing-extensions<4.6.0,>=4.5.0
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting pyjwt<2.8.0,>=2.7.0
  Downloading PyJWT-2.7.0-py3-none-any.whl (22 kB)
Collecting httpx-ws<0.4.0,>=0.3.1
  Downloading httpx_ws-0.3.1-py3-none-any.whl (12 kB)
Requirement already satisfied: httpx<0.25.0,>=0.24.0 in /usr/local/lib/python3.10/site-packages (from atproto->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 2)) (0.24.1)
Collecting dag-cbor<0.4.0,>=0.3.2
  Downloading dag_cbor-0.3.2-py3-none-any.whl (25 kB)
Requirement already satisfied: click<8.2.0,>=8.1.3 in /usr/local/lib/python3.10/site-packages (from atproto->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 2)) (8.1.3)
Collecting multiformats<0.3.0,>=0.2.1
  Downloading multiformats-0.2.1-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.0/56.0 kB 9.0 MB/s eta 0:00:00
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.10/site-packages (from black->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 4)) (3.6.0)
Requirement already satisfied: pathspec>=0.9.0 in /usr/local/lib/python3.10/site-packages (from black->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 4)) (0.11.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.10/site-packages (from black->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 4)) (1.0.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/site-packages (from black->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 4)) (2.0.1)
Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.10/site-packages (from black->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 4)) (23.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/site-packages (from bs4->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 5)) (4.12.2)
Collecting pyproject_hooks
  Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: pyflakes<3.1.0,>=3.0.0 in /usr/local/lib/python3.10/site-packages (from flake8->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 8)) (3.0.1)
Requirement already satisfied: pycodestyle<2.11.0,>=2.10.0 in /usr/local/lib/python3.10/site-packages (from flake8->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 8)) (2.10.0)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/site-packages (from flake8->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/site-packages (from pandas->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 11)) (2.8.2)
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 19.9 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 29.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/site-packages (from pandas->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 11)) (1.25.0)
Collecting dill>=0.2
  Downloading dill-0.3.6-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 41.8 MB/s eta 0:00:00
Collecting astroid<=2.17.0-dev0,>=2.15.4
  Downloading astroid-2.15.5-py3-none-any.whl (278 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.1/278.1 kB 36.5 MB/s eta 0:00:00
Collecting tomlkit>=0.10.1
  Downloading tomlkit-0.11.8-py3-none-any.whl (35 kB)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/site-packages (from pytest->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 13)) (1.0.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/site-packages (from pytest->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 13)) (1.1.1)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/site-packages (from pytest->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 13)) (2.0.0)
Requirement already satisfied: coverage[toml]>=5.2.1 in /usr/local/lib/python3.10/site-packages (from pytest-cov->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 14)) (7.2.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 17)) (1.26.16)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 17)) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 17)) (3.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 17)) (2023.5.7)
Requirement already satisfied: six in /usr/local/lib/python3.10/site-packages (from requests-mock->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 18)) (1.16.0)
Collecting requests-toolbelt!=0.9.0,>=0.8.0
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 166.1 MB/s eta 0:00:00
Collecting keyring>=15.1
  Downloading keyring-24.0.0-py3-none-any.whl (37 kB)
Collecting rich>=12.0.0
  Downloading rich-13.4.2-py3-none-any.whl (239 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.4/239.4 kB 18.3 MB/s eta 0:00:00
Collecting importlib-metadata>=3.6
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting rfc3986>=1.4.0
  Downloading rfc3986-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting pkginfo>=1.8.1
  Downloading pkginfo-1.9.6-py3-none-any.whl (30 kB)
Collecting readme-renderer>=35.0
  Downloading readme_renderer-40.0-py3-none-any.whl (14 kB)
Collecting decorator>=3.4.0
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting lazy-object-proxy>=1.4.0
  Downloading lazy_object_proxy-1.9.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 kB 111.0 MB/s eta 0:00:00
Requirement already satisfied: wrapt<2,>=1.11 in /usr/local/lib/python3.10/site-packages (from astroid<=2.17.0-dev0,>=2.15.4->pylint->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 12)) (1.15.0)
Collecting typing-validation
  Downloading typing_validation-1.0.0.post2-py3-none-any.whl (13 kB)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /usr/local/lib/python3.10/site-packages (from httpx<0.25.0,>=0.24.0->atproto->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 2)) (0.17.2)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/site-packages (from httpx<0.25.0,>=0.24.0->atproto->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: wsproto in /usr/local/lib/python3.10/site-packages (from httpx-ws<0.4.0,>=0.3.1->atproto->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/site-packages (from httpx-ws<0.4.0,>=0.3.1->atproto->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 2)) (3.7.0)
Collecting zipp>=0.5
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting jaraco.classes
  Downloading jaraco.classes-3.2.3-py3-none-any.whl (6.0 kB)
Collecting jeepney>=0.4.2
  Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 149.7 MB/s eta 0:00:00
Collecting SecretStorage>=3.2
  Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Collecting multiformats-config
  Downloading multiformats_config-0.2.0.post4-py3-none-any.whl (15 kB)
Collecting bases
  Downloading bases-0.2.1-py3-none-any.whl (35 kB)
Collecting bleach>=2.1.0
  Downloading bleach-6.0.0-py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 10.3 MB/s eta 0:00:00
Collecting docutils>=0.13.1
  Downloading docutils-0.20.1-py3-none-any.whl (572 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.7/572.7 kB 12.0 MB/s eta 0:00:00
Collecting Pygments>=2.5.1
  Downloading Pygments-2.15.1-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 25.6 MB/s eta 0:00:00
Collecting markdown-it-py>=2.2.0
  Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 106.7 MB/s eta 0:00:00
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/site-packages (from beautifulsoup4->bs4->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 5)) (2.4.1)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.24.0->atproto->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 2)) (0.14.0)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: cryptography>=2.0 in /usr/local/lib/python3.10/site-packages (from SecretStorage>=3.2->keyring>=15.1->twine->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 21)) (41.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/site-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 21)) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine->-r plugins/Auto-GPT-Plugins-master/requirements.txt (line 21)) (2.21)
Building wheels for collected packages: bs4, validators
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1257 sha256=663d7cb4631218689b6884355f006c36b4e2ca5a1d46ff6a027a73bdfab903bd
  Stored in directory: /tmp/pip-ephem-wheel-cache-93fqti9x/wheels/25/42/45/b773edc52acb16cd2db4cf1a0b47117e2f69bb4eb300ed0e70
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=efe4770d707d21e53413d1564d2a4a584f6afa6363cf8247aed15b1c0ffe26e5
  Stored in directory: /tmp/pip-ephem-wheel-cache-93fqti9x/wheels/f2/ed/dd/d3a556ad245ef9dc570c6bcd2f22886d17b0b408dd3bbb9ac3
Successfully built bs4 validators
Installing collected packages: webencodings, pytz, zipp, xmltodict, tzdata, typing-validation, typing-extensions, tomlkit, rfc3986, python-lorem, pyproject_hooks, pyjwt, Pygments, pkginfo, oauthlib, more-itertools, mdurl, lazy-object-proxy, jeepney, jaraco.context, docutils, dill, decorator, dacite, bleach, wolframalpha, validators, requests-toolbelt, requests-oauthlib, requests-mock, readme-renderer, pandas, newsapi-python, markdown-it-py, jaraco.classes, importlib-metadata, build, bs4, bases, astroid, tweepy, SecretStorage, rich, pylint, python-telegram-bot, keyring, httpx-ws, twine, multiformats-config, multiformats, dag-cbor, atproto
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.6.3
    Uninstalling typing_extensions-4.6.3:
      Successfully uninstalled typing_extensions-4.6.3
Successfully installed Pygments-2.15.1 SecretStorage-3.3.3 astroid-2.15.5 atproto-0.0.14 bases-0.2.1 bleach-6.0.0 bs4-0.0.1 build-0.10.0 dacite-1.8.1 dag-cbor-0.3.2 decorator-5.1.1 dill-0.3.6 docutils-0.20.1 httpx-ws-0.3.1 importlib-metadata-6.7.0 jaraco.classes-3.2.3 jaraco.context-4.3.0 jeepney-0.8.0 keyring-24.0.0 lazy-object-proxy-1.9.0 markdown-it-py-3.0.0 mdurl-0.1.2 more-itertools-9.1.0 multiformats-0.2.1 multiformats-config-0.2.0.post4 newsapi-python-0.2.7 oauthlib-3.2.2 pandas-2.0.2 pkginfo-1.9.6 pyjwt-2.7.0 pylint-2.17.4 pyproject_hooks-1.0.0 python-lorem-1.3.0.post1 python-telegram-bot-20.3 pytz-2023.3 readme-renderer-40.0 requests-mock-1.11.0 requests-oauthlib-1.3.1 requests-toolbelt-1.0.0 rfc3986-2.0.0 rich-13.4.2 tomlkit-0.11.8 tweepy-4.13.0 twine-4.0.2 typing-extensions-4.5.0 typing-validation-1.0.0.post2 tzdata-2023.3 validators-0.20.0 webencodings-0.5.1 wolframalpha-5.0.0 xmltodict-0.13.0 zipp-3.15.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
  Not loading plugin AutoGPTApiTools as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTApiTools) as the key.
  Not loading plugin AutoGPTSpacePlugin as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTSpacePlugin) as the key.
  Not loading plugin AutoGPTBaiduSearch as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBaiduSearch) as the key.
  Not loading plugin AutoGPTBingSearch as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBingSearch) as the key.
  Not loading plugin AutoGPTBluesky as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBluesky) as the key.
  Not loading plugin AutoGPTEmailPlugin as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTEmailPlugin) as the key.
  Not loading plugin AutoGPTNewsSearch as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTNewsSearch) as the key.
  Not loading plugin PlannerPlugin as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (PlannerPlugin) as the key.
  Not loading plugin AutoGPTRandomValues as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTRandomValues) as the key.
  Not loading plugin AutoGPTSceneXPlugin as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTSceneXPlugin) as the key.
  Not loading plugin AutoGPTTelegram as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTTelegram) as the key.
  Not loading plugin AutoGPTTwitter as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTTwitter) as the key.
  Not loading plugin AutoGPTWikipediaSearch as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTWikipediaSearch) as the key.
  Not loading plugin AutoGPTWolframAlphaSearch as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTWolframAlphaSearch) as the key.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 142, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/app/autogpt/plugins/__init__.py", line 256, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
  File "<frozen zipimport>", line 302, in load_module
  File "plugins/discord_plugin.zip/discord_plugin/__init__.py", line 6, in <module>
    from .discord_plugin import required_info_set, run_bot, wait_for_user_input, commandUnauthorized, Message, messagesToSend, userReply, waitingForReply, finishedLoggingIn
  File "plugins/discord_plugin.zip/discord_plugin/discord_plugin.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
```
AutoGPT thinks that "discord" is not installed when I did.

Here's the "pip install discord" log:

```Collecting discord
  Downloading discord-2.3.0-py3-none-any.whl (1.1 kB)
Collecting discord.py>=2.3.0 (from discord)
  Downloading discord.py-2.3.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.6 MB/s eta 0:00:00
Requirement already satisfied: aiohttp<4,>=3.7.4 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from discord.py>=2.3.0->discord) (3.8.4)
Requirement already satisfied: attrs>=17.3.0 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py>=2.3.0->discord) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py>=2.3.0->discord) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py>=2.3.0->discord) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py>=2.3.0->discord) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py>=2.3.0->discord) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py>=2.3.0->discord) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py>=2.3.0->discord) (1.3.1)
Requirement already satisfied: idna>=2.0 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from yarl<2.0,>=1.0->aiohttp<4,>=3.7.4->discord.py>=2.3.0->discord) (3.4)
Installing collected packages: discord.py, discord
Successfully installed discord-2.3.0 discord.py-2.3.0

**Comment by ebardet** [comment]
@TCFFan123 same here, how did you get out of this?

EDIT: finally got through with `poetry add discord.py`
